=== kruser/ziptie/org.ziptie.adapters/schema/adapters/AdapterMetadataSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="AdapterMetadata">
		<xs:annotation>
			<xs:documentation>
				Defines all of the metadata associated with a network
				device adapter for ZipTie. This includes information
				about the adapter itself, as well as metadata that can
				be used against data that is retrieved from the adapter.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="adapterId" minOccurs="1" maxOccurs="1" />
				<xs:element ref="supportedModelVersion" minOccurs="1" maxOccurs="1" />
				<xs:element ref="shortName" minOccurs="1" maxOccurs="1" />
				<xs:element ref="description" minOccurs="1" maxOccurs="1" />
				<xs:element ref="softwareVersionRegEx" minOccurs="1" maxOccurs="1" />
				<xs:element ref="biosVersionRegEx" minOccurs="1" maxOccurs="1" />
				<xs:element ref="lastRebootThreshold" minOccurs="1" maxOccurs="1" />
				<xs:element ref="errorForms" minOccurs="1" maxOccurs="1" />
				<xs:element ref="operationConstraints" minOccurs="1" maxOccurs="1" />
				<xs:element ref="discoveryMappings" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="adapterId">
		<xs:annotation>
			<xs:documentation>
				The ID of an adapter should be the same as the fully
				qualified package name for the Perl module that
				implements the adapter operations. For example:
				"ZipTie::Adapters::Cisco::IOS".
			</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="64" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="shortName">
		<xs:annotation>
			<xs:documentation>
				A short name for the adapter (30 characters or less).
			</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="30" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="description">
		<xs:annotation>
			<xs:documentation>
				A verbose description of the adapter and the network
				devices that it supports.
			</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="255" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="supportedModelVersion" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				Specifies which version of the ZipTie Element Document
				(ZED) model that the adapter produces.
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="biosVersionRegEx" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				Defines a regular expression to apply to text that
				describes information about the BIOS for a network
				device in order to extract the BIOS version
				number/string.
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="softwareVersionRegEx" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				Defines a regular expression to apply to text that
				describes information about the software/OS for a
				network device in order to extract the software/OS
				version number/string.
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="lastRebootThreshold" type="xs:int">
		<xs:annotation>
			<xs:documentation>
				The amount time (in seconds) to reference when
				determining whether or not
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="errorForms">
		<xs:annotation>
			<xs:documentation>
				Contains a set of regular expressions that can be used
				to match various error responses from a device.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="errorRegEx" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="errorRegEx" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				Defines a regular expression to apply to an error
				response from a device.
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="operationConstraints">
		<xs:annotation>
			<xs:documentation>
				Defines a set of operations that the associated adapter
				implements and supports.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="operation" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="operation">
		<xs:annotation>
			<xs:documentation>
				Defines an adapter operation that the adapter implements
				and supports. It is expected that the corresponding Perl
				module has a subroutine of the same name with the
				desired functionality.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="supportedProtocolSet" maxOccurs="unbounded" />
				<xs:element ref="restoreValidationRegex" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="supportedProtocolSet" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				Defines a set of protocols that the operation can use
				when communicating with a device. Each protocol in the
				set is delimited by a hyphen. For instance:
				"Telnet-TFTP-SNMP".
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	
	<xs:element name="restoreValidationRegex" type="xs:string">
        <xs:annotation>
            <xs:documentation>
                Defines a regular expression to be used against the name/path of
                a device configuration to determine whether or not it can be restored
                by the "restore" operation of the adapter.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

	<xs:element name="discoveryMappings">
		<xs:annotation>
			<xs:documentation>
				Defines the information that can be used to associate a
				newly discovered device with the adapter.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="matchRegex" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="matchRegex">
		<xs:annotation>
			<xs:documentation>
				Defines a set of regular expressions that can used
				against a specified SNMP data source to determine
				whether or not the adapter should be associated with a
				network device.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="multiline" type="xs:boolean"
				use="required">
				<xs:annotation>
					<xs:documentation>
						Whether or not the regular expression should be
						evaluated in multi-line mode.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="ignoreCase" type="xs:boolean"
				use="required">
				<xs:annotation>
					<xs:documentation>
						Whether or not the regular expression ignore
						case sensitivity when being applied.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="singleline" type="xs:boolean"
				use="required">
				<xs:annotation>
					<xs:documentation>
						Whether or not the regular expression should be
						used in single line mode.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="regex" type="xs:string"
				use="required">
				<xs:annotation>
					<xs:documentation>
						The regular expression to apply to the SNMP data
						source response.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="dataSource" use="required">
				<xs:annotation>
					<xs:documentation>
						The SNMP data source to apply the regular
						expression to. This can be either "sysDescr",
						"sysOid", or "sysName".
					</xs:documentation>
				</xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="sysDescr" />
                        <xs:enumeration value="sysOid" />
                        <xs:enumeration value="sysName" />
                    </xs:restriction>
                </xs:simpleType>
			</xs:attribute>
		</xs:complexType>

	</xs:element>

</xs:schema>

=== kruser/ziptie/ziptie.adapters.cisco.arrowpoint/scripts/ZipTie/Adapters/Cisco/ArrowPoint.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Cisco::ArrowPoint</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Cisco CSS/ArrowPoint</shortName>
    <description>Cisco Content Services Switches and ArrowPoint Load Balancers</description>
    <softwareVersionRegEx>([\d]+)\.([\d]+)\s+.*?\s+(\d+)?</softwareVersionRegEx>
    <biosVersionRegEx>([\d]+)\.([\d]+)</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
        <errorRegEx>% Invalid input detected</errorRegEx>
        <errorRegEx>Not in \S+ command</errorRegEx>
    </errorForms>
    <operationConstraints>
        <operation name="backup">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="restore">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
            <restoreValidationRegex>startup-config</restoreValidationRegex>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
    </operationConstraints>
    <discoveryMappings>
    <matchRegex dataSource="sysDescr" regex="Content Switch.*" ignoreCase="true" multiline="false" singleline="false"/>
    </discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.cisco.catos/scripts/ZipTie/Adapters/Cisco/CatOS.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Cisco::CatOS</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Cisco CatOS</shortName>
    <description>Cisco Catalyst Switches running CatOS</description>
    <softwareVersionRegEx>(\d+)\.(\d+)</softwareVersionRegEx>
    <biosVersionRegEx>(\d+)\.(\d+)</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
        <errorRegEx>Usage: [^\n\r]+[\n\r]\s*$</errorRegEx>
        <errorRegEx>Unknown command &quot;.*&quot;</errorRegEx>
    </errorForms>
    <operationConstraints>
        <operation name="backup">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-SCP</supportedProtocolSet>
        </operation>
        <operation name="restore">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-SCP</supportedProtocolSet>
            <restoreValidationRegex>config</restoreValidationRegex>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="syslogsetup">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="ntpserverchange">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="snmpcommunitychange">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="loginbanner">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="interfacechange">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="portvlan">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
    </operationConstraints>
    <discoveryMappings>
    	<matchRegex dataSource="sysDescr" regex="(CatOS|Catalyst Operating System)" singleline="false" multiline="false" ignoreCase="true"></matchRegex>
    </discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.cisco.cs500/scripts/ZipTie/Adapters/Cisco/CS500.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Cisco::CS500</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Cisco CS500</shortName>
    <description>Cisco CS500 Terminal Servers</description>
    <softwareVersionRegEx>([\d]+)\.*(\d*)\(*(\d*)\)*</softwareVersionRegEx>
    <biosVersionRegEx>([\d]+)\.*(\d*)\(*(\d*)\)*</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
    </errorForms>
    <operationConstraints>
        <operation name="backup">
            <supportedProtocolSet>Telnet</supportedProtocolSet>      
            <supportedProtocolSet>SSH</supportedProtocolSet>      
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
		<operation name="restore">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>      
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>      
        </operation>
    </operationConstraints>
    <discoveryMappings>
      <matchRegex dataSource="sysDescr" regex="CS Software.*" ignoreCase="true" multiline="false" singleline="false"/>
    </discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.f5.threedns/scripts/ZipTie/Adapters/F5/ThreeDNS.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::F5::ThreeDNS</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>F5 3DNS/BIG-IP v4</shortName>
    <description>F5 3DNS Wide-Area Load Balancers and BIG-IP Local Area Load Balancers running version 4.x.</description>
    <softwareVersionRegEx>(\d+)\.(\d+)</softwareVersionRegEx>
    <biosVersionRegEx>(\d+)\.(\d+)</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
        <errorRegEx>\S+: command not found</errorRegEx>
        <errorRegEx>cd: [^\n^\s]+: No such file or directory</errorRegEx>
        <errorRegEx>\S+: illegal option -- [^\n]+\nusage: \s+</errorRegEx>
        <errorRegEx>:\s*syntax error</errorRegEx>
    </errorForms>
    <operationConstraints>
        <operation name="backup">
            <supportedProtocolSet>SSH-SCP</supportedProtocolSet>
        </operation>
        <operation name="restore">
            <supportedProtocolSet>SSH-SCP</supportedProtocolSet>
            <restoreValidationRegex>.*</restoreValidationRegex>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
    </operationConstraints>
    <discoveryMappings>
        <matchRegex dataSource="sysDescr" regex="BIG-IP 4" singleline="false" multiline="false" ignoreCase="false"></matchRegex>
    </discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.nortel.passport/scripts/ZipTie/Adapters/Nortel/Passport.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Nortel::Passport</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Nortel Passport</shortName>
    <description>Nortel Passport Switches</description>
    <softwareVersionRegEx>([\d]+)\.([\d]+)\.([\d]+).*</softwareVersionRegEx>
    <biosVersionRegEx>([\d]+)\.([\d]+)\.([\d]+).*</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
        <errorRegEx>&quot;[^\n]+&quot; not found in path</errorRegEx>
        <errorRegEx>(Required|Optional) parameter [^\n]+ = [^\n]+ is out of range</errorRegEx>
    </errorForms>
    <operationConstraints>
        <operation name="backup">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="restore">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
            <restoreValidationRegex>.+</restoreValidationRegex>
        </operation>
    </operationConstraints>
    <discoveryMappings>
    <matchRegex dataSource="sysDescr" regex="Passport-8.*" singleline="false" multiline="true" ignoreCase="true"></matchRegex></discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.checkpoint.secureplatform/scripts/ZipTie/Adapters/CheckPoint/SecurePlatform.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::CheckPoint::SecurePlatform</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Check Point SecurePlatform</shortName>
    <description>Check Point SecurePlatform</description>
    <softwareVersionRegEx>\((\S\d+)\).+Build\s+(\d+)</softwareVersionRegEx>
    <biosVersionRegEx>(\S+)</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
    </errorForms>
    <operationConstraints>
        <operation name="backup">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="restore">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
            <restoreValidationRegex>rules.C|objects.C</restoreValidationRegex>
        </operation>
    </operationConstraints>
    <discoveryMappings>
        <matchRegex dataSource="sysDescr" regex="NGX" ignoreCase="false" multiline="false" singleline="false"/>
    </discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.juniper.screenos/scripts/ZipTie/Adapters/Juniper/ScreenOS.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Juniper::ScreenOS</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Juniper ScreenOS</shortName>
    <description>Juniper ScreenOS Firewalls (Netscreen)</description>
    <softwareVersionRegEx>([\d]+)\.*(\d*)\.*(\d*)r(\d*)\.*(\d)*</softwareVersionRegEx>
    <biosVersionRegEx>(\d+)\.?(\d*)</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
        <errorRegEx>[-]+unknown keyword</errorRegEx>
        <errorRegEx>[-]+command not completed</errorRegEx>
    </errorForms>
    <operationConstraints>
        <operation name="backup">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
		<operation name="restore">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
			<restoreValidationRegex>config</restoreValidationRegex>
        </operation>
    </operationConstraints>
    <discoveryMappings>
        <matchRegex dataSource="sysDescr" regex="netscreen" singleline="false" multiline="false" ignoreCase="true"/>
        <matchRegex dataSource="sysDescr" regex="SSG" singleline="false" multiline="false" ignoreCase="true"/>
    </discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.vyatta.ofr/scripts/ZipTie/Adapters/Vyatta/OFR.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Vyatta::OFR</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Vyatta OFR</shortName>
    <description>Vyatta Open Flexible Routers (OFR)</description>
    <softwareVersionRegEx>(\S+)</softwareVersionRegEx>
    <biosVersionRegEx>(\S+)</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
        <errorRegEx>syntax error, expecting</errorRegEx>
    </errorForms>
    <operationConstraints>
        <operation name="reboot">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="backup">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
    </operationConstraints>
    <discoveryMappings>
    </discoveryMappings>
</AdapterMetadata>
