=== kruser/ziptie/org.ziptie.adapters/schema/adapters/AdapterMetadataSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="AdapterMetadata">
		<xs:annotation>
			<xs:documentation>
				Defines all of the metadata associated with a network
				device adapter for ZipTie. This includes information
				about the adapter itself, as well as metadata that can
				be used against data that is retrieved from the adapter.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="adapterId" minOccurs="1" maxOccurs="1" />
				<xs:element ref="supportedModelVersion" minOccurs="1" maxOccurs="1" />
				<xs:element ref="shortName" minOccurs="1" maxOccurs="1" />
				<xs:element ref="description" minOccurs="1" maxOccurs="1" />
				<xs:element ref="softwareVersionRegEx" minOccurs="1" maxOccurs="1" />
				<xs:element ref="biosVersionRegEx" minOccurs="1" maxOccurs="1" />
				<xs:element ref="lastRebootThreshold" minOccurs="1" maxOccurs="1" />
				<xs:element ref="errorForms" minOccurs="1" maxOccurs="1" />
				<xs:element ref="operationConstraints" minOccurs="1" maxOccurs="1" />
				<xs:element ref="discoveryMappings" minOccurs="1" maxOccurs="1" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="adapterId">
		<xs:annotation>
			<xs:documentation>
				The ID of an adapter should be the same as the fully
				qualified package name for the Perl module that
				implements the adapter operations. For example:
				"ZipTie::Adapters::Cisco::IOS".
			</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="64" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="shortName">
		<xs:annotation>
			<xs:documentation>
				A short name for the adapter (30 characters or less).
			</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="30" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="description">
		<xs:annotation>
			<xs:documentation>
				A verbose description of the adapter and the network
				devices that it supports.
			</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:maxLength value="255" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="supportedModelVersion" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				Specifies which version of the ZipTie Element Document
				(ZED) model that the adapter produces.
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="biosVersionRegEx" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				Defines a regular expression to apply to text that
				describes information about the BIOS for a network
				device in order to extract the BIOS version
				number/string.
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="softwareVersionRegEx" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				Defines a regular expression to apply to text that
				describes information about the software/OS for a
				network device in order to extract the software/OS
				version number/string.
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="lastRebootThreshold" type="xs:int">
		<xs:annotation>
			<xs:documentation>
				The amount time (in seconds) to reference when
				determining whether or not
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="errorForms">
		<xs:annotation>
			<xs:documentation>
				Contains a set of regular expressions that can be used
				to match various error responses from a device.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="errorRegEx" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="errorRegEx" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				Defines a regular expression to apply to an error
				response from a device.
			</xs:documentation>
		</xs:annotation>
	</xs:element>

	<xs:element name="operationConstraints">
		<xs:annotation>
			<xs:documentation>
				Defines a set of operations that the associated adapter
				implements and supports.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="operation" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="operation">
		<xs:annotation>
			<xs:documentation>
				Defines an adapter operation that the adapter implements
				and supports. It is expected that the corresponding Perl
				module has a subroutine of the same name with the
				desired functionality.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="supportedProtocolSet" maxOccurs="unbounded" />
				<xs:element ref="restoreValidationRegex" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="supportedProtocolSet" type="xs:string">
		<xs:annotation>
			<xs:documentation>
				Defines a set of protocols that the operation can use
				when communicating with a device. Each protocol in the
				set is delimited by a hyphen. For instance:
				"Telnet-TFTP-SNMP".
			</xs:documentation>
		</xs:annotation>
	</xs:element>
	
	<xs:element name="restoreValidationRegex" type="xs:string">
        <xs:annotation>
            <xs:documentation>
                Defines a regular expression to be used against the name/path of
                a device configuration to determine whether or not it can be restored
                by the "restore" operation of the adapter.
            </xs:documentation>
        </xs:annotation>
    </xs:element>

	<xs:element name="discoveryMappings">
		<xs:annotation>
			<xs:documentation>
				Defines the information that can be used to associate a
				newly discovered device with the adapter.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="matchRegex" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="matchRegex">
		<xs:annotation>
			<xs:documentation>
				Defines a set of regular expressions that can used
				against a specified SNMP data source to determine
				whether or not the adapter should be associated with a
				network device.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="multiline" type="xs:boolean"
				use="required">
				<xs:annotation>
					<xs:documentation>
						Whether or not the regular expression should be
						evaluated in multi-line mode.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="ignoreCase" type="xs:boolean"
				use="required">
				<xs:annotation>
					<xs:documentation>
						Whether or not the regular expression ignore
						case sensitivity when being applied.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="singleline" type="xs:boolean"
				use="required">
				<xs:annotation>
					<xs:documentation>
						Whether or not the regular expression should be
						used in single line mode.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="regex" type="xs:string"
				use="required">
				<xs:annotation>
					<xs:documentation>
						The regular expression to apply to the SNMP data
						source response.
					</xs:documentation>
				</xs:annotation>
			</xs:attribute>
			<xs:attribute name="dataSource" use="required">
				<xs:annotation>
					<xs:documentation>
						The SNMP data source to apply the regular
						expression to. This can be either "sysDescr",
						"sysOid", or "sysName".
					</xs:documentation>
				</xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="sysDescr" />
                        <xs:enumeration value="sysOid" />
                        <xs:enumeration value="sysName" />
                    </xs:restriction>
                </xs:simpleType>
			</xs:attribute>
		</xs:complexType>

	</xs:element>

</xs:schema>

=== kruser/ziptie/ziptie.adapters.nokia.checkpoint/scripts/ZipTie/Adapters/Nokia/Checkpoint.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Nokia::Checkpoint</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Nokia Checkpoint</shortName>
    <description>Nokia Checkpoint Firewalls</description>
    <softwareVersionRegEx>(\d+)\.(\d+)</softwareVersionRegEx>
    <biosVersionRegEx>(\d+)\.(\d+)</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
        <errorRegEx>\S+: command not found</errorRegEx>
        <errorRegEx>cd: [^\n^\s]+: No such file or directory</errorRegEx>
        <errorRegEx>\S+: illegal option -- [^\n]+\nusage: \s+</errorRegEx>
    </errorForms>
    <operationConstraints>
        <operation name="backup">
            <supportedProtocolSet>SSH-SCP</supportedProtocolSet>
        </operation>
        <operation name="restore">
            <supportedProtocolSet>SSH-SCP</supportedProtocolSet>
            <restoreValidationRegex>.*</restoreValidationRegex>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
    </operationConstraints>
    <discoveryMappings>
        <matchRegex dataSource="sysDescr" regex="IPSO" singleline="false" multiline="false" ignoreCase="true"></matchRegex>
    </discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.cisco.securityappliance/scripts/ZipTie/Adapters/Cisco/SecurityAppliance.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Cisco::SecurityAppliance</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Cisco Security Appliances</shortName>
    <description>Cisco Security Appliances (PIX, ASA, FWSM)</description>
    <softwareVersionRegEx>(\d+)\.(\d+)\((\d+)\)</softwareVersionRegEx>
    <biosVersionRegEx>(\d+)\.(\d+)</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
        <errorRegEx>Type help or ['?]+ for a list of available commands</errorRegEx>
        <errorRegEx>% Invalid input detected</errorRegEx>
    </errorForms>
    <operationConstraints>
        <operation name="backup">
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>Telnet</supportedProtocolSet>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
		<operation name="restore">
			<supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <restoreValidationRegex>startup-config</restoreValidationRegex>
        </operation>
        <operation name="ntpserverchange">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="syslogsetup">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="snmpcommunitychange">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="loginbanner">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
    </operationConstraints>
    <discoveryMappings>
	    <matchRegex dataSource="sysDescr" regex="(PIX|Adaptive Security Appliance|Firewall Services Module)" singleline="false" multiline="false" ignoreCase="true"></matchRegex>
	</discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.foundry.fastiron/scripts/ZipTie/Adapters/Foundry/FastIron.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Foundry::FastIron</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Foundry FastIron</shortName>
    <description>Foundry FastIron and ServerIron Devices</description>
    <softwareVersionRegEx>(\d+)\.(\d+)(\.(\S+))?</softwareVersionRegEx>
    <biosVersionRegEx>(\d+)\.(\d+)(\.(\S+))?</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
	<errorRegEx>%Syntax(.+)%</errorRegEx>
	<errorRegEx>%Invalid(.+)%</errorRegEx>
    </errorForms>
    <operationConstraints>
        <operation name="backup">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
		<operation name="restore">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <restoreValidationRegex>startup-config</restoreValidationRegex>
        </operation>
    </operationConstraints>
    <discoveryMappings>
	<matchRegex dataSource="sysDescr" regex="Foundry\sNetworks.+(ServerIron|FastIron|IronWare)" ignoreCase="true" multiline="false"	singleline="false"/>
    </discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.marconi.atmswitch/scripts/ZipTie/Adapters/Marconi/ATMSwitch.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Marconi::ATMSwitch</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Marconi ATM Switch</shortName>
    <description>Marconi ATM Switches</description>
    <softwareVersionRegEx>(\d+)\.(\d+)</softwareVersionRegEx>
    <biosVersionRegEx>(\d+)\.(\d+)</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
    </errorForms>
    <operationConstraints>
        <operation name="backup">
            <supportedProtocolSet>Telnet-SNMP</supportedProtocolSet>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
    </operationConstraints>
    <discoveryMappings>
		<matchRegex dataSource="sysDescr" regex="Marconi.*" singleline="false" multiline="false" ignoreCase="true"/>
    </discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.cisco.waas/scripts/ZipTie/Adapters/Cisco/WAAS.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Cisco::WAAS</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Cisco WAAS Platforms</shortName>
    <description>Cisco Wide-Area Application Services devices</description>
    <softwareVersionRegEx>V{0,1}(\d+)\.?(\d*)\(?(\d*)\.?(\d*)([A-Za-z]*)\)?([A-Za-z]*)(\d*)\(?(\d*)\.?(\d*)([A-Za-z]*)\)?\w*</softwareVersionRegEx>
    <biosVersionRegEx>V{0,1}(\d+)\.?(\d*)\(?(\d*)\.?(\d*)([A-Za-z]*)\)?([A-Za-z]*)(\d*)\(?(\d*)\.?(\d*)([A-Za-z]*)\)?\w*</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
        <errorRegEx>% Invalid input detected at</errorRegEx>
        <errorRegEx>% (Ambiguous|Unknown) command</errorRegEx>
    </errorForms>
    <operationConstraints>
        <operation name="reboot">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="backup">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
        </operation>
        <operation name="restore">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
    </operationConstraints>
    <discoveryMappings>
        <matchRegex dataSource="sysDescr" regex="Cisco\s+(Wide Area.+)" ignoreCase="true" multiline="false" singleline="false"/>
    </discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.enterasys.verticalhorizon/scripts/ZipTie/Adapters/Enterasys/VerticalHorizon.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Enterasys::VerticalHorizon</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Enterasys VerticalHorizon</shortName>
    <description>Enterasys Vertical Horizon Switches</description>
    <softwareVersionRegEx>(\d+)\.(\d+)</softwareVersionRegEx>
    <biosVersionRegEx>(\d+)\.(\d+)</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
    </errorForms>
    <operationConstraints>
        <operation name="backup">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
		<operation name="restore">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
        </operation>
    </operationConstraints>
    <discoveryMappings>
		  <matchRegex dataSource="sysDescr" regex="Vertical Horizon.*" ignoreCase="true" multiline="false" singleline="false"/>
    </discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.extreme.xos/scripts/ZipTie/Adapters/Extreme/XOS.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Extreme::XOS</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Extreme XOS</shortName>
    <description>XOS</description>
    <softwareVersionRegEx>(\d+)\.(\d+)</softwareVersionRegEx>
    <biosVersionRegEx>(\d+)\.(\d+)</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
    </errorForms>
    <operationConstraints>
        <operation name="backup">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="loginbanner">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
    </operationConstraints>
    <discoveryMappings>
        <matchRegex dataSource="sysDescr" regex="ExtremeWare X[0O]S" ignoreCase="true" multiline="false" singleline="false"/>
    </discoveryMappings>
</AdapterMetadata>

=== kruser/ziptie/ziptie.adapters.nortel.baystack/scripts/ZipTie/Adapters/Nortel/BayStack.metadata.xml
<?xml version="1.0" encoding="utf-8" ?>
<AdapterMetadata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="AdapterMetadataSchema.xsd">
    <adapterId>ZipTie::Adapters::Nortel::BayStack</adapterId>
    <supportedModelVersion>1.0</supportedModelVersion>
    <shortName>Nortel BayStack</shortName>
    <description>Nortel BayStack Family Switches (BayStack, BPS)</description>
    <softwareVersionRegEx>[Vv]*([\d]+)\.*(\d*)\.*(\d*)\.*(\d*)</softwareVersionRegEx>
    <biosVersionRegEx>[Vv]*([\d]+)\.*(\d*)</biosVersionRegEx>
    <lastRebootThreshold>5</lastRebootThreshold>
    <errorForms>
        <errorRegEx>Previous operation is currently in progress</errorRegEx>
        <errorRegEx>Load host not found or not responding</errorRegEx>
        <errorRegEx>TFTP unknown error</errorRegEx>
        <errorRegEx>Operation aborted</errorRegEx>
    </errorForms>
    <operationConstraints>
        <operation name="reboot">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
        <operation name="backup">
            <supportedProtocolSet>Telnet-TFTP-SNMP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP-SNMP</supportedProtocolSet>
        </operation>
        <operation name="restore">
            <supportedProtocolSet>Telnet-TFTP</supportedProtocolSet>
            <supportedProtocolSet>SSH-TFTP</supportedProtocolSet>
            <restoreValidationRegex>^/?config</restoreValidationRegex>
        </operation>
        <operation name="commands">
            <supportedProtocolSet>Telnet</supportedProtocolSet>
            <supportedProtocolSet>SSH</supportedProtocolSet>
        </operation>
    </operationConstraints>
    <discoveryMappings>
        <matchRegex dataSource="sysDescr" regex="Business Policy Switch|BayStack|Ethernet Routing Switch" ignoreCase="true" multiline="false" singleline="false"/>
    </discoveryMappings>
</AdapterMetadata>
